\connect coolgeo;
ALTER DATABASE coolgeo SET search_path=public,postgis;
DROP TABLE IF EXISTS paystats CASCADE;
DROP TABLE IF EXISTS postal_codes CASCADE;
CREATE TABLE postal_codes (the_geom GEOMETRY, code INTEGER, id INTEGER PRIMARY KEY);
CREATE TABLE paystats(amount NUMERIC(20,4),p_month DATE,p_age VARCHAR(10),p_gender VARCHAR(1),postal_code_id INTEGER
, id INTEGER PRIMARY KEY);
ALTER ROLE :USER_RWX VALID UNTIL 'infinity';
ALTER ROLE :USER_RX VALID UNTIL 'infinity';
GRANT CONNECT ON DATABASE coolgeo TO :USER_RWX;
GRANT CONNECT ON DATABASE coolgeo TO :USER_RX;
ALTER TABLE paystats OWNER TO :USER_RWX;
ALTER TABLE postal_codes OWNER TO :USER_RWX;
GRANT ALL PRIVILEGES ON paystats TO :USER_RWX;
GRANT ALL PRIVILEGES ON postal_codes TO :USER_RWX;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO :USER_RX;
